start "" "./exe/sensors/pressureSensor.exe -config="../configs/demo/sensor1.yaml"
start "" "./exe/sensors/tempSensor.exe  -config="../configs/demo/sensor2.yaml"
start "" "./exe/sensors/windSensor.exe  -config="../configs/demo/sensor3.yaml"
start "" "./exe/sensors/pressureSensor.exe -config="../configs/demo/sensor4.yaml"
start "" "./exe/sensors/tempSensor.exe  -config="../configs/demo/sensor5.yaml"
start "" "./exe/sensors/windSensor.exe  -config="../configs/demo/sensor6.yaml"