mqtt:
  url: ssl://5891f12726364e0cbda5ae805fad5a45.s2.eu.hivemq.cloud
  port: 8883
  qos: 2
  id: alerte-manager
  login: tparchid
  password: IMTAtlantique44
maxValue:
  maxWindValue: 10.0
  maxPresValue: 6.0
  maxTempValue: 1025.0